version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "18:48"
    commit-message: 
      prefix: ":allow_up:"
      prefix-development: ":allow_up:"
      include: "scope"
